services:
  - type: web
    name: icodeschool-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: FRONTEND_URL
        value: https://icodeschool-eight.vercel.app
      - key: NODE_VERSION
        value: "20"
